import React from 'react'
import Head from 'next/head'
import styles from './BuyGold.module.css'
import ClickableChips from './Chips'
import { useState,useEffect } from 'react'

export const BuyGold = () => {
    const [btnClrbr,setBtnclrbr] = useState(true)
    const [btnClrbg,setBtnclrbg] = useState(false)
     const [zeroFlag,setZeoflag] = useState(false)
     const [gramZeroFlag,setGZeroflag] = useState(false)
    const [validationErr,setValiderr] = useState(false)
    // const [showRs,setShowrs] = useState(true)
    const [flag,setFlag] = useState(true)
    const [showGrams,setShowgrams] = useState(true)
    const [money,setMoney] = useState(5000)
    const [gram,setgram]=useState(0);
    const [gramQty,setGramqty] = useState(1)
    const [gramtors,setGramtors] = useState(0)
   
  
    let btn_class1 = btnClrbr ? "ActiveButton" : "DeselectButton";
    let btn_class2 = btnClrbg ? "ActiveButton" : "DeselectButton";
  
    let handleClrbg = () => {
    setBtnclrbr(false)
    setBtnclrbg(true)
    setFlag(false)
  }
  let handleClrbr = () => {
    setBtnclrbr(true)
    setBtnclrbg(false)
    setFlag(true)
    
  }
  let handleRsinp = (e) => {
      setMoney(e.target.value)
  
   }
   let handleGraminp = (e) => {
    setGramqty(e.target.value)
   }
   
  useEffect(() => {
  console.log(money);
    if(money <= 0 || money > 100000){
      for(let i=0;i<=money.length;i++){
        if(money[i] == 0){
          console.log('loop');
          setValiderr(true)
        }
          //  else {
          //   if(mony)
          //   // setValiderr(false)
          //  } 
      }  
  }
    if(money === '' || money > 100000){
      setShowgrams(false)
      setZeoflag(true)
      // setValiderr(true)
    }
    else { 
      setShowgrams(true)
      setZeoflag(false) 
    }
    let res = money * 0.000186135
    setgram(() => (Math.round(res * 100) / 100).toFixed(4));
  }, [money]);
  
  useEffect(() => {
    setGramtors(() => gramQty * 5372.43);
    if(gramQty == '' || gramQty <= 0 ){
      setGZeroflag(true)
    } else {
      setGZeroflag(false)
    }
  }, [gramQty]);
  
    return (
      <div className={styles.container}>
      
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
      <main>
      <div style={{backgroundColor:'#222',color:'gold',alignItems:'center',justifyContent:'center',display:'flex'}}>
        <div>
        <h1>Buy Gold</h1>
        Start Buying Gold :)
        </div>
      </div>
        <div width="256px" className={`${styles.hKNTrH}  ${styles.hFjJjE}`}>
          <button name="Buy in Rupees" className={` ${btn_class1}`} onClick={handleClrbr} style={{fontSize: 14,}}>Buy in Rupees</button>
          <button name="Buy in Grams" className={` ${btn_class2}`}  style={{fontSize: 14,}}
           onClick={handleClrbg}>Buy in Grams</button>
        </div>
      
        {flag ? (
          <>
          <div>
          <div className={`${styles.cepcQc}`} style={{marginTop:30}}>
            <div className=" iJSplQ">
              <div className={` ${styles.igmqli}`}>
                <input className={` ${styles.dpgxGA}`} value={`${money}`} onChange={handleRsinp}></input>
              { validationErr ? <div style={{color: 'red', fontSize: 12 }}>Please enter amount between 1 and 100000</div> : '' }  
                </div>
              </div>
            </div>
          </div>
          <div className={` ${styles.cepcQc}`}>
            <span className={` ${styles.gBnbja}`}>{gram} grams</span>
          </div>
        
        <div className={`${styles.cepcQc}`} style={{marginTop:10}}> 
        <div className={` ${styles.hczcQu}`}>Enter amount or choose from below </div>
      </div>
  
      <ClickableChips chipamt={setMoney} flag={flag}/>
      <div className=" gOXTlf">
        <span className={` ${styles.gXgxmc}`}>Popular</span>
      </div>
   
  
          {/* {zeroFlag ? (<>
        
            <div className={`${styles.cepcQc}`} style={{marginTop:10}}> 
            <div className={` ${styles.hczcQu}`}>Enter amount or choose from below </div>
          </div>
    
          <ClickableChips chipamt={setMoney} flag={flag}/>
          <div className=" gOXTlf">
            <span className={` ${styles.gXgxmc}`}>Popular</span>
          </div>
          </>) : ""} */}
          
          </> ):(<>
            <div>
              <div className={` ${styles.cepcQc}`} style={{marginTop:30}}>
                <div className=" iJSplQ">
                  <div className={` ${styles.igmqli}`}>
                    <input className={` ${styles.dpgxGA}`} value={`${gramQty}`}   onChange={handleGraminp}></input>
                  { validationErr ? <div style={{color: 'red', fontSize: 12 }}>Please enter a value between 1 and 18.6136</div> : '' }  
                 
                    </div>
                  </div>
                </div>
              </div>
           
               <div className={` ${styles.cepcQc}`}>
            <span className={` ${styles.gBnbja}`}>₹{gramtors}</span>
          </div> 
        
        <div className={` ${styles.cepcQc}`}> 
          <div className={` ${styles.hczcQu}`}>Enter grams or choose from below </div>
        </div>
  
        <ClickableChips grams={setGramqty} flag={flag}/>
  
  
  
          {/* {gramZeroFlag ? (<>
        
              <div className={` ${styles.cepcQc}`}> 
                <div className={` ${styles.hczcQu}`}>Enter grams or choose from below </div>
              </div>
  
              <ClickableChips grams={setGramqty} flag={flag}/>
  
            </>) : ""} */}
                </>
              )}
        </main>
     
      </div>
    )
}
